//------------------------------------------------------------------------------
// <auto-generated>
//     קובץ זה נוצר ידנית משום ש-Visual Studio לא יצר אוטומטית designer.cs עבור עמוד זה
//     (הקבצים נוצרו מחוץ לעורך של Visual Studio ולא דרך אשף "Add New Item").
// </auto-generated>
//------------------------------------------------------------------------------
namespace CarShop
{
    public partial class CarMatch
    {
        protected global::System.Web.UI.WebControls.TextBox txtTripDetails;

        protected global::System.Web.UI.WebControls.Button btnFindCar;

        protected global::System.Web.UI.WebControls.Label lblStatus;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl resultBox;

        protected global::System.Web.UI.WebControls.Label lblResult;
    }

}