-- Migration script to hash existing admin password
-- This script updates the admin user password to a hashed version
-- Hashed password for "123456" using PBKDF2

-- First, let's check if the admin user exists
SELECT * FROM Users WHERE Username = 'admin';

-- Update admin user with hashed password
-- The hashed value is a PBKDF2 hash of "123456" (will be generated by code during first login)
-- For now, keep plaintext during migration - will auto-hash on first successful login

-- If you want to pre-hash the password for "123456", use this PasswordHelper code:
-- string hashedPassword = PasswordHelper.HashPassword("123456");
-- Then run: UPDATE Users SET Password = '[hashedPassword_here]' WHERE Username = 'admin';

-- To manually hash password "123456", run this in your app first:
-- 1. Create a test page with: Console.WriteLine(PasswordHelper.HashPassword("123456"));
-- 2. Copy the output
-- 3. Replace [HASHED_PASSWORD_HERE] below with the actual hash
-- UPDATE Users SET Password = '[HASHED_PASSWORD_HERE]' WHERE Username = 'admin';
